### ISSUE TITLE
Ex 3 lack of directions.

### ISSUE THREAD

**Issue by ItsSNOWMOBILE** [INF1007-Gabarits/2024A-TP01#2]
Je travaillais sur le troisième exercice où nous devions utiliser la formule de la distance. Il faudrait clarifier quelle valeur doit être prise en compte pour "g", car 9,8 et 9,81 donnent des résultats très différents dans ce contexte. Par ailleurs, il faudrait préciser que math.sin utilise des radians et NON des degrés, alors que l'entrée est donnée en degrés.

**Comment by Fanevark** [comment]
Oui, j'ai ajouté cette correction dans [ce commmit](https://github.com/INF1007-Gabarits/2024A-TP01/commit/892b6fbe6c3b7ebbb1b99cab2e58a9cda52b9ca6). Dans la section où je parle de la fonction sinus, j'ai ajouté de faire attention à l'unité, afin de ne pas vendre la mèche et vous inciter à lire et comprendre les détails des fonctions que vous utilisez.
