### ISSUE TITLE
test_tp1.py is flawed.

### ISSUE THREAD

**Issue by ItsSNOWMOBILE** [INF1007-Gabarits/2024A-TP01#3]
Exécuter le test vous donnera toujours un résultat "fail" à cause de petits problèmes : accents, espaces, tabulations ou même parenthèses. Je recommanderais de passer à l'autograde de GitHub pour cela. Cela embrouille vraiment les gens quant à savoir si leur code est correct ou non.

exemple:

```- De quelle nationalité est l'athlète ? Quel est son nom? Date du record? Dans quelle discipline?Dans une catégorie specifique? Quel est le 
record?
?                                                                                                                     ^
+ De quelle nationalité est l'athlète ? Quel est son nom ? Date du record ? Dans quelle discipline ? Dans une catégorie spécifique ? Quel est le record ?
?                                                       +                +                        + +                     ^       +
           +
  Nouveau Record:
- ------------------
+ --------------------
? ++
- 1/8/2024
- Natation - 200M Papillon
+ 1/8/2024 - Natation - 200M Papillon:
? +++++++++++                        +
        Summer McIntosh (CAN) - 2:3.03```

**Comment by Fanevark** [comment]
À la sortie du TP, les sorties entre le GIF, les tests et le tableau ne correspondaient pas, je m'en excuse. En ce moment dans les tests, vous avez exactement le formattage à suivre, il vous est possible de comparer exactement les sorties, de plus, unittest vous indique à quels endroits est-ce que cela ne concorde pas quand les erreurs sont subtiles. En mettant ce formattage, je voulais aussi que vous mettiez en pratique les caractères blancs comme les tabulations ou les retours à la ligne. Sans ces informations et pouvoir regarder à quel formattage on s'attends, cet exercice n'aurait aucun sens. 

Par rapport à l'autograde de Github, étant donné que les premiers TP ne se font pas sur Git, ça ne marche pas trop. Il serait néanmoins pertinent pour les TP suivants d'avoir un pipeline qui note automatiquement les résultats.
